spring:
  main:
    banner-mode: "off"
  profiles:
    active: test

logging:
  file: storage.log

rabbitmq:
  queue: products.queue

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: never
      cache:
        time-to-live: 20000ms
    info:
      enabled: true

server:
  port: 8091
  servlet:
    context-path: /storage

info:
  build:
    group: @project.groupId@
    artifact: @project.artifactId@
    version: @project.version@
    name: @project.name@

---
spring.profiles: local

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://mysql-container:3306/products?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    initialization-mode: always
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: validate

  rabbitmq:
    host: rabbitmq-container
    port: 5672
    username: guest
    password: guest

logging:
  file: storage.log
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core:
      JdbcTemplate: DEBUG
      StatementCreatorUtils: TRACE

---
spring.profiles: test

spring:

  datasource:
    url: jdbc:tc:mysql:5.7.22://localhost:3306/products?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    initialization-mode: never
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop

mq:
  info:

    exchange-name: localhost.exchange
    queue-name: localhost.queue
    dead-letter-queue-name: user.update.dead-letter